/* 
  *   Speech.java generated by speechmod 
 */   

package Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  


	PROVIDE_DATE("[SPEECH][SPEECHIN][PROVIDE_DATE]",1500), //COMPLEMENTAR
	CANCEL("[SPEECH][SPEECHIN][CANCEL]",1500), //REDUNDANTE
	;


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
