/* 
  *   Speech.java generated by speechmod 
 */   

package Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  


	PROVIDE_DATE("[SPEECH][PROVIDE_EVENT_DATE]",5000), //COMPLEMENTAR
	PROVIDE_DAY("[SPEECH][PROVIDE_EVENT_DAY]",5000), //COMPLEMENTAR
	DELETE_EVENT("[SPEECH][DELETE_EVENT]",5000), //REDUNDANTE
	;


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
